### ISSUE TITLE
problems with uploadBlob

### ISSUE THREAD

**Issue by dcsan** [tautologer/easy-bsky-bot-sdk#8]
I spent some time trying to get `uploadBlob` method to work.

from what I can see the basic XRPC calls to AT proto aren't returning as expected. 
also the size of the image we send is different from the response.

Arta (kite dev) also tried to help me debug a bit. One thing might be that you are somehow overriding the fetch method used?

I see you have your own fetch.ts is that being injected into the agent?

I'll send a PR for review but at this point it's not quite working yet.
my code fails on `uploadBlob` here

https://gist.github.com/dcsan/98fa835c133395ae979923f4ff3582fa#file-makeembed-ts-L19

```
$ cd examples/basic
$ just dev
cd ../.. && tsc
pwd
/Users/dc/dev/bsky/easy-bsky-bot-sdk/examples/basic
npm run dev

> basic-bsky-bot@0.0.1 dev
> ts-node index.ts

Please consider using a handle with ".bot." or "-bot" in it to indicate to users that this account is a bot.
(node:47941) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file exists [
  {
    "imageUrl": "./testdata/test-cat.jpg",
    "encoding": "image/jpeg"
  }
]
read data [
  {
    "length": 46721,
    "data": "object",
    "bytes": "object"
  }
]
uncaught error in main: XRPCInvalidResponseError: The server gave an invalid response and may be out of date.
    at ServiceClient.call (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/xrpc/src/client.ts:117:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeEmbed (/Users/dc/dev/bsky/easy-bsky-bot-sdk/lib/embed.js:63:22) {
  status: 2,
  error: 'Invalid Response',
  success: false,
  lexiconNsid: 'com.atproto.repo.uploadBlob',
  validationError: ValidationError: Output/blob should be a blob ref
      at blob (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/validators/blob.ts:15:14)
      at validate (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/validators/complex.ts:38:19)
      at validateOneOf (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/util.ts:66:27)
      at object (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/validators/complex.ts:127:25)
      at validateOneOf (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/util.ts:65:27)
      at assertValidOneOf (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/util.ts:90:15)
      at assertValidXrpcOutput (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/validation.ts:53:12)
      at Lexicons.assertValidXrpcOutput (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/lexicon/src/lexicons.ts:198:12)
      at ServiceClient.call (/Users/dc/dev/bsky/easy-bsky-bot-sdk/node_modules/@atproto/xrpc/src/client.ts:114:29)
      at processTicksAndRejections (node:internal/process/task_queues:95:5),
  responseBody: {
    blob: {
      '$type': 'blob',
      ref: [Object],
      mimeType: 'image/jpeg',
      size: 165415
    }
  }
}
error: Recipe `dev` failed on line 25 with exit code 1
```

**Comment by dcsan** [comment]
other refs

https://gist.github.com/trozzelle/38ac90c5721c1fa1b6de488f8ca0eb11
https://github.com/robpc/bluesky-photo-test/blob/main/src/index.ts#L85-L113

https://github.com/bluesky-social/atproto/blob/main/packages/pds/tests/file-uploads.test.ts

**Comment by dcsan** [comment]
yeah I got it working in about 10 mins in a separate repo

https://staging.bsky.app/profile/storytime.bsky.social
https://github.com/dcsan/bb2/blob/main/src/utils/atp/makeEmbed.ts

so there's something about this framework that is breaking ATP calls.

**Comment by dcsan** [comment]
FWIW i'm runnnig node18 and get this warning

`(node:50675) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time`

in both repos
